name: Push on Epitech repository

on:
  pull_request:
    branches:
      - dev

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: push to Epitech
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.KEY}}
          script: |
            git config --global user.email "cyril1.cabrolier@epitech.eu"
            git config --global user.name "Cyril Cabrolier"
            git checkout $CI_COMMIT_REF_NAME
            git push repo="git@github.com:EpitechMscProPromo2025/T-YEP-600-TLS-6-1-finalproject-aurelien.schmit.git" --force